export const AppConfig = {
    GITHUB_ACCESS_TOKEN : process.env.GITHUB_ACCESS_TOKEN,
    BITBUCKET_USERNAME : process.env.BITBUCKET_USERNAME,
    BITBUCKET_ACCESS_TOKEN : process.env.BITBUCKET_ACCESS_TOKEN
};
